### PR TITLE
Docs: update copy delivery process documentation

### LINKED ISSUE #2218: Update documentation to reflect changes in the copy delivery process
Revise this section of our documentation to include support for Ditto and any other changes in the process that result from adopting Ditto.

https://docs.calitp.org/benefits/product-and-design/copy-delivery/

## Acceptance Criteria

- [ ] Documentation accurately reflects current process.

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #2218 

This PR updates the "Copy delivery process" docs to reflect workflow involving Ditto and Crowdin. Design (@srhhnry) did the bulk of the work for capturing the details of our process. We worked in a Google Doc to iterate on the changes.

Also see #2388 for more context on the work that went into these updates.

### CODE REVIEW

**Comment by angela-tran** [comment]
https://benefits-2466--cal-itp-previews.netlify.app/product-and-design/copy-delivery/

**Comment by angela-tran** [comment]
Noticing some weird formatting issues... putting into draft.

**Review by thekaveman — APPROVED** [review]
This looks great :memo:

**Comment by angela-tran** [comment]
Merging this in now. We can always open follow-up PRs if we notice something is inaccurate.

**Pull request merged**
