### PR TITLE
Chore: change SacRT copy to say "bus" instead of "light rail"

### PR DESCRIPTION
**Pull request by angela-tran**
Part of #2505 

There were 3 places I found that mentioned "light rail":
- "Get a reduced fare on SacRT light rail when you tap to ride" - agency index page
- "Cal-ITP doesn’t save any of your information. All SacRT transit benefits reduce fares by 50% for light rail." - eligibility index
- "You were not charged anything today. When boarding SacRT light rail, tap this card and you will be
    charged a reduced fare. You will need to re-enroll if you choose to change the card you use to pay for transit service." - enrollment success

For the Spanish translations, I did my best to map "bus" in for SacRT based on the copy for SBMTD. @lalver1 Maybe you can check my work to see if it makes sense to a Spanish speaker?

SBMTD entries in `es/LC_MESSAGES/django.po` are right below SacRT's entries, so you can compare them pretty easily.

### CODE REVIEW

**Comment by angela-tran** [comment]
Hmm, I'm not sure why the Django migration+messages check is failing... I did run `./bin/makemessages.sh` and commit the changes. :slightly_frowning_face:

**Comment by lalver1** [comment]
The translations look great @angela-tran!

**Comment by angela-tran** [comment]
> Hmm, I'm not sure why the Django migration+messages check is failing... I did run `./bin/makemessages.sh` and commit the changes. 🙁
>...

I think this is due to how GitHub pull requests are technically running on a hidden branch that compares the base and target branches.

I am able to reproduce the failing check locally with these steps:
- Create a script at the project root-level containing what the check runs, call it `check.sh`:
```bash
./bin/makemessages.sh

set -x # show commands

git add benefits

# message files are up-to-date if the only differences are from the updated timestamp
if echo $(git diff --cached --shortstat) | grep -q '2 files changed, 2 insertions(+), 2 deletions(-)';
then
  exit 0;
else
  exit 1;
fi
```
- Fetch the hidden branch into your repo as a local branch named `troubleshoot-makemessages` (or whatever you want): 
   - `git fetch origin pull/2507/head:troubleshoot-makemessages`
- Check it out
   - `git checkout troubleshoot-makemessages`
- Run the script
   - `./check.sh`

My output
```
calitp@7b79b09cfce6:/calitp/app$ ./check.sh 
processing locale en
processing locale es
++ git add benefits
++ grep -q '2 files changed, 2 insertions(+), 2 deletions(-)'
+++ git diff --cached --shortstat
++ echo 2 files changed, 7 'insertions(+),' 5 'deletions(-)'
++ exit 1
```

**Comment by angela-tran** [comment]
Ok, never mind. I'm not sure what state I was in before, but I just re-checked out `chore/sacrt-copy-update`, ran `./bin/makemessages.sh`, and there _were_ changes! Minor formatting things that don't actually change the copy. :roll_eyes: 

Committed those, and the check should pass now

**Review by lalver1 — APPROVED** [review]
Looks good! 👍

**Pull request merged**
