### PR TITLE
fix: update package-lock.json

### PR DESCRIPTION
**Pull request by afeld**
I didn't run an update or anything; these showed up after starting the devcontainer 🤷

### CODE REVIEW

**Comment by thekaveman** [comment]
This shows up almost every time. If you can figure out why that would be great! We tend to update it when updating the tests.

**Comment by thekaveman** [comment]
You can just `git restore` on it to get rid of any local changes.

**Comment by afeld** [comment]
If it shows up every time, why wouldn't we commit it?

**Comment by afeld** [comment]
Again, this doesn't update the package, just reflects dependencies that should have been in the lock file in the first place (but weren't for some reason).

**Comment by thekaveman** [comment]
Here's a recent commit where these exact lines where added: https://github.com/cal-itp/benefits/pull/378/commits/a59837ce2ed71bf38c7b092f79479dfc36306dda

And in the same PR, a later commit where they were removed: https://github.com/cal-itp/benefits/pull/378/commits/f05551087ecc3e5c5859881c8c0fe04bcf0b9709

I don't know why these lines in particular continue to show up and disappear (no matter what we commit). If you can find the root cause, I would definitely like to know what it is!

**Comment by afeld** [comment]
Gotcha. My guess is a NPM CLI version difference. Won't worry about it for now. Thanks!

**Pull request closed without merging**
