### PR TITLE
Agency Index: Mobile edit from Design

### PR DESCRIPTION
**Pull request by machikoyasuda**
Two requests from @srhhnry 

1. Make Agency Index page show more of the background image on very small phones (iPhone SE): Increased the minimum height of the container to show more image for mobile only:

image

Compared with on Dev

image

### CODE REVIEW

**Comment by srhhnry** [comment]
Amazing! Thank you. Can we make it 24px on radio button distance instead of 25? Just for that 8x continuity.

**Comment by machikoyasuda** [comment]
We can work on this together in person on Thursday @srhhnry

**Comment by machikoyasuda** [comment]
- #1079 
- Form validation testing
- Use a form without mouse

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran This super small PR is now ready for review. Use the Chrome/Firefox devtools to simulate the iPhone 12 size/width.

**Review by angela-tran — COMMENTED** [review]
This definitely looks better for smaller screens. For longer phones though, what do you think about all the space between the bottom of the Visa card and the box with text? Is it too much space?

### Smaller screen (iPhone SE 2nd Gen)
**Current dev-benefits** vs. **this branch**
image

### Longer screen (iPhone 12/13 Pro Max)
**Current dev-benefits** vs. **this branch**
image

**Comment by machikoyasuda** [comment]
@angela-tran Yes - Sarah approved this design interaction in person.

**Review by angela-tran — APPROVED** [review]

**Pull request merged**
