### PR TITLE
Fix: Docker platform issue

### LINKED ISSUE #1357: Bug: Fix platform for Apple hardware
Benefits VS Code dev container does not open on Apple hardware.

## To Reproduce

1. Use an Apple machine
2. Clone repo
3. Run `bin/build.sh`
4. See error https://github.com/cal-itp/eligibility-server/issues/247
5. Open VS Code, run `Re-build without Cache and Re-open in Container`
6. See error described here https://github.com/cal-itp/benefits/pull/1353

## Expected behavior

App would open in dev container successfully. User can run app locally, use Git and all other commands necessary for development.

## Screenshots

Screenshots here https://github.com/cal-itp/benefits/pull/1353

## Desktop (please complete the following information)

- OS: Mac / M1

## Related issues
- https://github.com/moby/moby/issues/42893
- https://github.com/docker/cli/issues/3286
- https://github.com/moby/moby/issues/42893
- https://forums.docker.com/t/not-finding-local-unprefixed-docker-image-in-the-local-cache/113297/2

### PR DESCRIPTION
**Pull request by machikoyasuda**
fixes #1357 and https://github.com/cal-itp/eligibility-server/issues/247

see https://github.com/cal-itp/benefits/pull/1353 in favor of this solution for background 

## Testing
- [x] Test on Mac @machikoyasuda 
- [x] Test on Windows @angela-tran 

## How to test
- Run `bin/build.sh`
- Open VS Code and run`Re-build without Cache and re-open in container`
- Wait for all extensions to install
- Run the app in Debug mode
- Try `git status`
- Run commands, like `pytest`
- Close VS Code
- Open VS Code and run `Re-open in container` (using the cached dev container) and test steps again

### CODE REVIEW

**Review by thekaveman — APPROVED** [review]
Took me a few `Dev Containers: Rebuild and Reopen in Container` cycles to get the Python extension working correctly, but I don't think that has anything to do with these changes

👍

**Comment by thekaveman** [comment]
@angela-tran can you please confirm these changes work for you before we merge?

**Review by angela-tran — APPROVED** [review]
@thekaveman @machikoyasuda I can confirm that this works for me too. I was able to rebuild the base `client` image and rebuild the devcontainer.

At first, I got an error about `EventScrubber` not being found, but after rebuilding the `client` image, that went away. I guess my `sentry_sdk` version was off somewhere. Anyways, all good 👍

**Comment by machikoyasuda** [comment]
@angela-tran Just out of curiosity, was the first VS Code container install slower for you?

**Comment by machikoyasuda** [comment]
Note: This PR closes this bug issue in Eligibility Server: https://github.com/cal-itp/eligibility-server/issues/247

**Comment by angela-tran** [comment]
> @angela-tran Just out of curiosity, was the first VS Code container install slower for you?

Not that I remember 🤔 The first build always takes more time than subsequent ones that use cached layers I think, and it didn't stand out to me as taking longer than normal

**Pull request merged**
