### PR TITLE
Show retry button on enrollment/retry page

### LINKED ISSUE #1755: Retry button is missing
There is supposed to be a "Try again" button on the "retry" page. The user sees this page if there was a verification failure or error upon submitting the payment processor form.

## To Reproduce

1. Go through the SBMTD senior flow
2. Verify your senior eligibility
3. Try enrolling in the discount by submitting the payment processor form
4. See a page that says you can try again but doesn't provide a button for you to go anywhere

## Expected behavior

The user can use a "Try again" button to go back to the enrollment/index

## Screenshots

image

## Desktop
- OS: seen on Mac and Windows
- Browser: seen on Chrome and Firefox

## Additional context

We saw this while testing SBMTD senior flow on the dev Benefits site.

### PR DESCRIPTION
**Pull request by machikoyasuda**
fix #1755 

## What this PR does
- Pass `retry_button` as `True` to the `enrollment/retry` page, so that the button appears

### CODE REVIEW

**Review by thekaveman — COMMENTED** [review]
This definitely works, but I'm curious why we even have this `retry_button` context and the `{% if ... %}` check in our template. 

Don't we always want to show a retry button on the retry page? Could we just remove this context variable and the template check?

**Comment by machikoyasuda** [comment]
@thek

**Comment by angela-tran** [comment]
I looked through the Git history a little, and it seems like in https://github.com/cal-itp/benefits/commit/4c498956a05108bf3daf94c39b0e0fbd1f927905 we just forgot to remove `if retry_button` from the template.

**Comment by thekaveman** [comment]
> @thekaveman Yeah I wondered the same thing. As long as this Retry page/template is not called from other methods, I don't think we would need the check. Should I just remove?

Thanks for the find @angela-tran.

Yep @machikoyasuda I think we are good to remove this.

**Review by thekaveman — APPROVED** [review]

**Pull request merged**
