### PR TITLE
Fix: Use rem calculation for 18px font

### PR DESCRIPTION
**Pull request by machikoyasuda**
related to #778

## How to test this PR
- Test the app in 200% on Chrome, Firefox, Safari on Desktop - Everything should be clickable/not blocked
- Test the app in 200% on mobile browsers - Everything should be clickable/not blocked
- @angela-tran What other kind of testing should we be doing for this check?

Reference: https://dev-benefits.calitp.org/help

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Hrm.. site looks kinda messed up at 200% zoom on Mobile:
image

Site looks/acts like the Mobile site (more or less) at 200% zoom on Desktop:
image

**Comment by angela-tran** [comment]
> @angela-tran What other kind of testing should we be doing for this check?

We should also test changing our browser's default font size to 32px and see if text is scaling appropriately and that spacing still looks ok. Currently I see on dev-benefits.calitp.org that the "Espanol" button and the footer links are not respecting the browser font size.

image

**Comment by machikoyasuda** [comment]
> > @angela-tran What other kind of testing should we be doing for this check?
> 
> We should also test changing our browser's default font size to 32px and see if text is scaling appropriately and that spacing still looks ok. Currently I see on dev-benefits.calitp.org that the "Espanol" button and the footer links are not respecting the browser font size. (I think your PR fixes this; I haven't had a chance to test on your branch yet.)
> 
> image

Test this PR at 32px font size on Desktop and Mobile: The Español button and Footer links respect the browser font size.

image

image

**Comment by machikoyasuda** [comment]
After doing some more local testing, I think I am going to make a follow-up PR to this to convert more (if not all) of the pixels in styles.css to rems. I'd like to convert at least these: Footer link height, Radio button sizing and spacing, Previous button, Header/Footer). But for now, I am going to keep this PR small and focused only on font size.

**Review by angela-tran — APPROVED** [review]

**Pull request merged**
