### PR TITLE
Feat: track verifier in session

### LINKED ISSUE #321: Track EligibilityVerifier in user session
## Background

As part of #317 the application will need maintain the user's selected `EligibilityVerifier`.

We can do this using the existing [`session` framework](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py) which keeps everything local to the user in secure cookies.

## Tasks

- [x] Add a [new key `_VERIFIER = "verifier"`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L28) for use elsewhere
- [x] Create a new function `verifier()` that uses the key to get the `EligibilityVerifier` instance corresponding to the saved value from the session; see [`agency()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L35) and [`eligibility()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L87) as examples
- [x] Update the [`update()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L192) function to accept a new kwarg `verifier=None`; if not None and it is a valid `EligibilityVerifier` instance, store the `id` in the request's session using the key
- [x] Update the [`reset()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L134) function to also clear the verifier
- [x] Update the [`context_dict()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L52) function to add the new key/value - this shows up in the debug bar
- [ ] Store the agency's first verifier in session (for now) when an agency is configured
- [ ] Retrieve the verifier from session to give to the API client

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #321

### CODE REVIEW

**Review by thekaveman — APPROVED** [review]
Looks great!! 👍

**Review by thekaveman — CHANGES_REQUESTED** [review]
Actually, sorry - I'm going to go a bit off scope from #321.

Can you also make the change to store/retrieve the verifier from session in the views? For now you can store in the same place that the agency is stored (use the first verifier as usual). And then retrieve before the API Client is initialized.

Then we can test/see that the verifier is really being tracked in the session.

**Comment by angela-tran** [comment]
> Actually, sorry - I'm going to go a bit off scope from #321.
> 
> Can you also make the change to store/retrieve the verifier from session in the views? For now you can store in the same place that the agency is stored (use the first verifier as usual). And then retrieve before the API Client is initialized.
> 
> Then we can test/see that the verifier is really being tracked in the session.

Sure, not a problem

**Comment by thekaveman** [comment]
Added those items to #321. Thanks! This will get us in better position for #323 too.

**Review by thekaveman — APPROVED** [review]
This is great. Now running locally, I can see that the session starts without an `agency` or a `verifier`:

image

And then both are set once the `agency` is selected:

image

And going back to the homepage correctly resets the `verifier`!

**Pull request merged**
