### PR TITLE
Enrollment Success: Redesign page to have no image

### LINKED ISSUE #565: Enrollment: Success (signed out): Use the full-screen with no image
image

Use the fullscreen view instead

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #565 
closes https://github.com/cal-itp/benefits/issues/513

## What this PR does

image
image

## How to test
1. Test MST / Senior flow of getting to enrollment succecss page and then logging out from the success page
2. Test MST / Courtesy Card flow of getting to enrollment success page

### CODE REVIEW

**Review by angela-tran — APPROVED** [review]
This looks good to me!

**Comment by machikoyasuda** [comment]
https://github.com/cal-itp/benefits/issues/513

**Review by thekaveman — DISMISSED** [review]

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran I added 1 more commit to take care of https://github.com/cal-itp/benefits/issues/513 - Now ready for re-review

**Review by thekaveman — APPROVED** [review]
Amazing!

**Pull request merged**
