### PR TITLE
Refactor devcontainer and localhost files

### PR DESCRIPTION
**Pull request by thekaveman**
## What this PR does

Before this PR, the `localhost/` directory was used to manage aspects of the devcontainer, sample data, etc.

This PR seeks to normalize some of this treatment with our evolving best practices in other repos:

* move the devcontainer related files into a `.devcontainer/` directory
* splits the sample Django data from a single `client.json` file to multiple per-model files
* reuse the Django TransitAgency sample fixture in Cypress tests
* remove the sample `localhost/keys/` files; sample keys are still available in Django fixtures
* remove `localhost/` altogether

### `docker compose build --no-cache client`

image

### Rebuild and Reopen the devcontainer

image

### `F5` + `npx cypress run`

image

image

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Note: Don't forget to `cd .devcontainer && cp .env.sample .env` before rebuilding this container

**Review by machikoyasuda — APPROVED** [review]
I like how you used the app fixtures in the integration tests.

I ran this app locally, got the app, docs, tests all running 👍🏼 The doc changes look good too.

**Comment by thekaveman** [comment]
Thanks @machikoyasuda! I was thinking about this a little more and I don't really like that huge `require(../../..)` path - it seems brittle if things are reorganized etc.

I like your original tests going to the local `fixtures/` directory, so I added a small proxy file in there that grabs the agency data from the Django fixture. That way tests can always go to the local `fixtures/` folder and we can figure out how to get the data from there. Does that make sense?

**Comment by angela-tran** [comment]
@thekaveman Refactor looks good! I was able to rebuild and reopen the container and run the tests.

image

I noticed there are some lingering instances of `localhost/` in some doc files:
 - .dockerignore
 - docs/deployment/README.md
 - documentation.md
 
image

**Review by angela-tran — CHANGES_REQUESTED** [review]
@thekaveman Refactor looks good! I was able to rebuild and reopen the container and run the tests.

image

I noticed there are some lingering instances of `localhost/` in some files:
 - .dockerignore
 - docs/deployment/README.md
 - documentation.md
 
image

**Comment by thekaveman** [comment]
Rebase on `dev` incoming, to incorporate changes from #187.

Will also address @angela-tran finds! Thank you for that.

**Comment by thekaveman** [comment]
@angela-tran:

> I noticed there are some lingering instances of `localhost/` in some files

Fixed!

image

**Review by angela-tran — APPROVED** [review]
💯

**Pull request merged**
