### PR TITLE
Feat: add auth button to Eligibility start page

### LINKED ISSUE #380: Add sign on button on Eligibility Start page
## Background

Build on #374 to work in the template specific to this page. This task is to simply add the button with accurate visual look/feel _when needed_; implementing the functionality is in #375.

### Placement, look, and feel

As a guide to what is covered under this task, see the following visual mock:
 
image

Note that the exact location and look of this button may change.

## Tasks

* [x] New style for _External action_ button using `#2b6597` as the outline and text color, squared corners; see [CA State Template buttons](https://template.webstandards.ca.gov/sample/buttons.html) for more
* [x] Grab the arrow icon from Figma and save as a local `.svg` to use in the button
* [x] Show the new button if the feature flag in #372 is enabled
* [x] Otherwise a button to forward to the `eligibility:confirm` page as normal

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #380.

This PR just adds the button with a minimal amount of styling for the button itself; the placement on the page still needs to coordinate with #395 

To get this to work, we also needed sample AuthProvider data, which is included as a fixture here. Rebuild your database to get these changes:

```bash
rm django.db

bin/init.sh
```

The existing `eligibility.spec.js` UI tests were re-written for the non-`AuthProvider` path, to keep the tests close to their original state as possible. A new UI test block was introduced for the Eligibility start page, with a test that verifies the Login.gov button appears.

## What it looks like

**Normal**

image

**Hover**

image

### CODE REVIEW

**Comment by thekaveman** [comment]
Working on updating the tests so they pass with the changes

**Comment by angela-tran** [comment]
Taking a look 👀

**Comment by thekaveman** [comment]
This is weird, can't figure out why this one test is not passing here. It's passing locally:

Running `ui` tests in the devcontainer (same command the workflow runs):

image

Result:

image

**Comment by thekaveman** [comment]
They all pass from `npm run cypress:open` outside the devcontainer:

image

**Comment by angela-tran** [comment]
@thekaveman It fails for me locally:
image
image

Trying to debug.

**Comment by angela-tran** [comment]
Oh, I hadn't rebuilt my database. It all passes for me locally. ✅ 

🤔

**Comment by thekaveman** [comment]
Maybe this is GitHub Actions caching something? I'm going to try opening a brand new PR

**Comment by thekaveman** [comment]
The failure screenshot from the Workflow run definitely has the wrong button (hard to see, but fully filled in at the top): 

Multiple verifier, with AuthProvider Eligibility start page spec -- Has a Login gov button (failed)

**Comment by thekaveman** [comment]
Couldn't get this test to pass in a new branch/PR either #404 

Adding a `skip()` for now to keep this moving.

**Review by angela-tran — APPROVED** [review]
These changes look good to me!

**Comment by thekaveman** [comment]
@machikoyasuda if you can look at this PR too, specifically the changes I made to the tests; do they make sense? Can you get the `specs/ui/eligibility.spec.js` to run locally?

**Review by machikoyasuda — APPROVED** [review]

**Pull request merged**
