### PR TITLE
Fix: configure and use latest test eligibility server

### PR DESCRIPTION
**Pull request by angela-tran**
This PR resurrects changes from #468 since the TODO has been resolved by cal-itp/eligibility-server#101.

I rebased the commit and made some fixes to account for all the work that's gone into `dev`.

### CODE REVIEW

**Review by thekaveman — APPROVED** [review]
Nice work! 🤖

**Review by thekaveman — COMMENTED** [review]
Started up the devcontainer on this branch, loaded the sample data only.

I had assumed `A1234567` and `Garcia` would verify for `ABC` - but it does not.

In the Docker logs for `server`, I can see the call coming in and returning success:

```console
[04/Aug/2022 19:14:01] "GET /verify HTTP/1.1" 200 -
```

**Comment by angela-tran** [comment]
@thekaveman Can you try with `B2345678` and `Hernandez` instead?

**Comment by thekaveman** [comment]
@angela-tran Yes `Hernandez` worked

**Comment by angela-tran** [comment]
> @angela-tran Yes `Hernandez` worked

Awesome, I think this means it's working as expected. [`Hernandez`](https://github.com/cal-itp/benefits/pull/847/files#diff-06e2c554bea6e7b973ea3bfcd5cf25df4c85c96778d60a576ce2ec3fa3376bbfR2) or [`Jones`](https://github.com/cal-itp/benefits/pull/847/files#diff-06e2c554bea6e7b973ea3bfcd5cf25df4c85c96778d60a576ce2ec3fa3376bbfR4) should be the only records that work with the sample "MST Courtesy Cardholder" (`type2`) discount option since the server checks the `type` when it [reads from its database](https://github.com/cal-itp/eligibility-server/blob/main/eligibility_server/verify.py#L96).

**Comment by thekaveman** [comment]
Doh, of course - I see now that the sample `type2` is verified by our test server 👍

**Review by thekaveman — APPROVED** [review]

**Pull request merged**
