### PR TITLE
Feat: veterans auth provider

### LINKED ISSUE #1428: Define AuthProvider for veterans

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #1428 

Defines an `AuthProvider` object meant for use with the veteran flow. Dummy default values are used for the client ID, authority, scope, and claim.

Updates app settings in Terraform to reflect different secrets for the two `AuthProvider` objects.

### To test locally
Set these environment variables

> AUTH_PROVIDER_CLIENT_ID=`<client ID from Key Vault>`
> AUTH_PROVIDER_AUTHORITY=`<IdG URL from Key Vault>`
> SENIOR_AUTH_PROVIDER_SCOPE=`<scope from Key Vault>`
> SENIOR_AUTH_PROVIDER_CLAIM=`<claim from Key Vault>`
> VETERAN_AUTH_PROVIDER_SCOPE=<value from https://cal-itp.slack.com/archives/C037Y3UE71P/p1685556379722939?thread_ts=1684790050.367569&cid=C037Y3UE71P>
> VETERAN_AUTH_PROVIDER_CLAIM=<value from https://cal-itp.slack.com/archives/C037Y3UE71P/p1685556379722939?thread_ts=1684790050.367569&cid=C037Y3UE71P>

### Before merging
 - [ ] Set secrets for senior- and veteran-specific auth provider values in dev and test

### CODE REVIEW

**Comment by angela-tran** [comment]
@thekaveman @machikoyasuda Would you be ok with keeping this PR's scope to just the backend changes for making the veteran flow accessible? 

I think there are a number of ways we could refactor the way this Login.gov logo works and don't want that discussion to block these changes. Also, we need a ticket for hiding the "Sign out" link for the veteran flow based on [this Slack thread](https://cal-itp.slack.com/archives/C037Y3UE71P/p1687820548748279?thread_ts=1687815526.509399&cid=C037Y3UE71P).

image

Let me know what you think.

**Comment by machikoyasuda** [comment]
@angela-tran yea I agree with you - this PR should be focused on back-end changes only. I would want the Login.gov button changes to be in a different ticket. 

And yes, we need a new ticket to take care of the 2 different Sign Out logic, and make sure that's consistent on all the places there is a Sign Out link or text (Enrollment Success, Elig Error, Enrollment Index, Payment Error).

**Comment by thekaveman** [comment]
> and make sure that's consistent on all the places there is a Sign Out link or text (Enrollment Success, Elig Error, Enrollment Index, Payment Error).

See my comment on https://github.com/cal-itp/benefits/issues/1442#issuecomment-1608572537

**Comment by angela-tran** [comment]
Thanks for creating that ticket @thekaveman and for your feedback too @machikoyasuda . This PR is ready for review

**Review by machikoyasuda — APPROVED** [review]

**Comment by angela-tran** [comment]
I just caught an issue where the MST agency didn't have `veteran` in its list of supported types. Will push a commit shortly

**Review by thekaveman — APPROVED** [review]
LGTM! Works locally as expected with a test VA.gov sandbox account for ID.me

**Comment by machikoyasuda** [comment]
Posting this here also for posterity: https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts/verification_test_accounts.md

**Review by machikoyasuda — APPROVED** [review]

**Comment by machikoyasuda** [comment]
Note: Created a draft ticket to reflect the need to change the CSS for https://github.com/cal-itp/benefits/pull/1439#issuecomment-1608453472

https://github.com/orgs/cal-itp/projects/17/views/2?pane=issue&itemId=31902043

**Pull request merged**
