### PR TITLE
add page on student discount use case

### PR DESCRIPTION
**Pull request by afeld**
Closes https://calitp.teamwork.com/index.cfm#/tasks/26219542.

Screenshot of new students page

### CODE REVIEW

**Comment by thekaveman** [comment]
The Teamwork task seems to be deleted? Or I don't have permission to view it.

I'm not super keen on having this be a top-level page, for something that is planned/not part of the tech stack yet. What about reorganizing into a `use-cases/` directory, we could also fill out more current/planned use-cases as part of our growing roadmap.

**Comment by afeld** [comment]
[You should now have Teamwork access.](https://cal-itp.slack.com/archives/C03E9VBEA8K/p1658257497493789?thread_ts=1658256469.952359&cid=C03E9VBEA8K)

>  What about reorganizing into a `use-cases/` directory

It's not immediately obvious to me how to do that without creating an empty Use Cases page, which I think would be confusing. This is such a low-traffic site… Would you mind if we leave it there for the moment, and set up a redirect later when we have other pages to group with it?

**Comment by thekaveman** [comment]
> It's not immediately obvious to me how to do that without creating an empty Use Cases page, which I think would be confusing. This is such a low-traffic site… Would you mind if we leave it there for the moment, and set up a redirect later when we have other pages to group with it?

Sure, wrote up #809 to track

**Comment by afeld** [comment]
Now live at https://docs.calitp.org/benefits/students/.

**Pull request merged**
