### PR TITLE
fix(Terraform): downgrade App Service plan

### PR DESCRIPTION
**Pull request by afeld**
Fixes https://github.com/cal-itp/benefits/issues/1142. Holding on merging due to https://github.com/cal-itp/benefits/issues/1142#issuecomment-1363117266.

## Post-merge TODOs

- [ ] Confirm Eligibility Server connection still works
- [ ] Update allowed IP addresses

### CODE REVIEW

**Comment by afeld** [comment]
Confirmed that the RAM and Storage of the [the B1 Plan](https://azure.microsoft.com/en-us/pricing/details/app-service/windows/) should be sufficient.

**Review by thekaveman — APPROVED** [review]
LGTM but want @angela-tran to weigh-in / be ready with any IP changes for Server

**Comment by afeld** [comment]
> be ready with any IP changes for Server

Yep, captured as TODOs above.

**Review by angela-tran — APPROVED** [review]
Looks good to me. @afeld I am assuming you'll take care of updating the IP addresses for eligibility-server?

**Comment by afeld** [comment]
Yep!

**Comment by afeld** [comment]
Confirmed the outbound IP addresses weren't changed. Possible it changes them in _some_ cases? 🤷 We should keep an eye on that for release to test/prod.

The switch caused [eight minutes of downtime](https://cal-itp.slack.com/archives/C022HHSEE3F/p1672864539418619). Not aware of a way to avoid that without more significant engineering.

**Comment by afeld** [comment]
Correction: I had spot-checked a few of the IP addresses, but didn't check all. Copied and pasted the list over again to be safe, which also [removed a bunch that we didn't need anymore](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=161&view=logs&j=e2b2897c-f736-5615-5c9c-c20ddcd4aa73&t=ce99383a-5c73-5e0e-b029-4934b8ac07e5&l=64) because they corresponded to the App Service slot.

**Pull request merged**
