### PR TITLE
Feat: EligibilityVerifier custom text

### LINKED ISSUE #319: Update EligiblityVerifier model to support custom text content
## Background

In #317, we identified a number of user-facing text elements on various pages during the Eligibility Verification process that must be configurable based on how the user is verifying their eligibility.

A straightforward way to represent these variable text elements is store them with the `EligibilityVerifier` model instances. We'll store the text that represents the `msgid` in a `.po` language file instead of storing the actual text content directly, to maintain the app's internationalization (see also #318).

While the lines of ownership for some text content can be blurred between `EligibilityType` and `EligibilityVerifier`, for now we'll store everything with the verifier for ease of management.

## Attributes to add

Consider this list to be a starting point based on an initial read of the new UI designs. Each of these should be added as a `TextField` to the [model class](https://github.com/cal-itp/benefits/blob/dev/benefits/core/models.py#L56), and we can just update the [initial migration](https://github.com/cal-itp/benefits/blob/dev/benefits/core/migrations/0001_initial.py) since most of the new fields can't be null and we'll just rebuild the database from scratch anyway.

* [x] `selection_label`: Shown when the user is selecting from a list of verifiers
* [x] `selection_label_description`: (optional) Additional helper text shown under the main label
* [x] `instructions_content_title`: The title shown on the instructions page for the verifier
* [x] `instructions_item_name`: The name given to the verification item needed
* [x] `instructions_item_description`: The description given to the verification item needed
* [x] `instructions_blurb`: The main text blurb shown on the instructions page
* [x] `form_title`: The title of the form page
* [x] `form_content_title`: The title of the form page's content
* [x] `form_blurb`: The main text blurb shown above the form
* [x] `form_sub_label`: The label for the `sub` field on the form
* [x] `form_sub_placeholder`: The placeholder for the `sub` field on the form
* [x] `form_name_label`: The label for the `name` field on the form
* [x] `form_name_placeholder`: The placeholder for the `name` field on the form
* [x] `unverified_title`: The title of the unverified page
* [x] `unverified_content_title`: The title of the unverified page's content
* [x] `unverified_blurb`: The main text blurb shown on the unverified page

## Additional tasks

* [x] Update fixtures with new model attributes, and copy in the corresponding `msgid` from the `*.po` files

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #319

### CODE REVIEW

**Comment by thekaveman** [comment]
Before we merge this, we have to update the fixture file(s) in `dev`

**Review by thekaveman — CHANGES_REQUESTED** [review]
Can you please rename the fields I had added previously, to line up with the new ones you're adding (which I like better):

* `form_sub_pattern` (instead of `regex`)
* `form_name_max_length`

**Review by thekaveman — CHANGES_REQUESTED** [review]
One more thing too - this is going to run migrations and create the fields, but the fixtures aren't updated to contain the new data. I updated the ticket with a new task for this.

**Comment by angela-tran** [comment]
> Can you please rename the fields I had added previously, to line up with the new ones you're adding (which I like better):
> 
>     * `form_sub_pattern` (instead of `regex`)
> 
>     * `form_name_max_length`

I like that better too. Made this change in [7ed9492](https://github.com/cal-itp/benefits/pull/331/commits/7ed94920fbdc08acef0f6637742d0edf999d8525). 

Note that I also reordered the fields in the model definition and fixtures to group them better. I left the order alone in the migration code to keep my changes minimal.

**Comment by angela-tran** [comment]
> One more thing too - this is going to run migrations and create the fields, but the fixtures aren't updated to contain the new data. I updated the ticket with a new task for this.

Made this change in [984bf73](https://github.com/cal-itp/benefits/pull/331/commits/984bf73dde0ba2eaf156b06006d038a9580441b4). Some notes:
 - I copied over existing msgids that correspond to the new fields. I imagine we'll rename some of these msgids in #324, namely the ones that have `.index` in their msgid but will be a part of the instructions page.
 - I am also leaving it up to #332 and #324 to add new PO file entries for `selection_label`/`selection_label_description` and `form_sub_placeholder`/`form_name_placeholder`, respectively.

**Comment by angela-tran** [comment]
Some open questions came up when I was looking at the PO entries. We could resolve them either as a part of this PR or as separate tickets/PRs. I noted the questions in the ticket ([#319](https://github.com/cal-itp/benefits/issues/319#issuecomment-1072620807)).

**Comment by angela-tran** [comment]
@thekaveman I updated the description in #319 and made those changes. This is ready for re-review 🔍

**Comment by thekaveman** [comment]
@angela-tran Looking at this again 👀

**Review by thekaveman — APPROVED** [review]
This is great!

I cleaned the compiled language files and rebuilt my local database; no reported errors, the migrations run, fixtures are imported, and language files compiled:

```bash
calitp@93063145f6a8  ~/app (feat/verifier-custom-text)
$ rm django.db 

calitp@93063145f6a8  ~/app (feat/verifier-custom-text)
$ rm benefits/locale/**/*.mo

calitp@93063145f6a8  ~/app (feat/verifier-custom-text)
$ bin/init.sh 
[21/Mar/2022 23:38:46] DEBUG benefits.core.urls:41 Register path converter: TransitAgencyPathConverter
[21/Mar/2022 23:38:46] DEBUG benefits.urls:34 Skip url registrations for admin
Operations to perform:
  Apply all migrations: core, sessions
Running migrations:
  Applying core.0001_initial... OK
  Applying sessions.0001_initial... OK
[21/Mar/2022 23:38:47] DEBUG benefits.core.urls:41 Register path converter: TransitAgencyPathConverter
[21/Mar/2022 23:38:47] DEBUG benefits.urls:34 Skip url registrations for admin
Installed 9 object(s) from 5 fixture(s)
superuser: Django not configured for Admin access
processing file django.po in /home/calitp/app/benefits/locale/en/LC_MESSAGES
processing file django.po in /home/calitp/app/benefits/locale/es/LC_MESSAGES
```

Launching the local app with `F5` I can successfully verify a test user:

image

**Pull request merged**
