### PR TITLE
fix(header): move debug bar out of <header>, remove header height css

### PR DESCRIPTION
**Pull request by machikoyasuda**
#435 

Fixes most of 435.

Moves the `DEBUG BAR` _out_ of the `<header>` HTML element, which has a lot of CSS added on it. 

## Test this PR

image

Open any page _with_ this PR, and then open another tab of the same page -- with the Debug bar entirely removed. (You can remove it by commenting out the Debug bar HTML code, or also removing it from the DOM within DevTools). The spacing of everything under the header _should remain the same_.

### CODE REVIEW

**Comment by thekaveman** [comment]
I'll just add @machikoyasuda we can put this e.g. at the bottom of the page, under the footer, if that would be more helpful?

**Comment by machikoyasuda** [comment]
@thekaveman I considered that too, but this placement is fine - HTML/CSS-wise too.

**Comment by angela-tran** [comment]
Reviewing this / launching locally 👀

**Review by angela-tran — APPROVED** [review]
Works very well now 👍

**Pull request merged**
