### PR TITLE
Refactor: remove Cypress

### LINKED ISSUE #2534: Remove Cypress

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #2534 

This PR removes Cypress from our project. 

The plan is to use Playwright for any automated front-end testing, and we will start with automating the smoke tests that are part of our release process (see #2504). 

Eventually, we may add the type of automated front-end testing that these Cypress tests were meant to do, which was something more like front-end validation / regression / QA testing.

I went through all the Cypress tests we have, and none of them appear to be a critical test that we need to keep around while moving on to Playwright. Rather than waiting until we've replaced these tests with corresponding Playwright tests, I think we should just go ahead and remove Cypress wholesale. It's probably better anyways for us to revisit when exactly a front-end QA test is warranted.

<details><summary>Just for historical record purposes, here is a list of tickets that show our history with trying to use Cypress:</summary>

- Added Cypress to devcontainer **(Nov 2021)**
   - https://github.com/cal-itp/benefits/pull/122
- Added more Cypress tests, and enabled them to run on pull requests **(Nov 2021)**
   - https://github.com/cal-itp/benefits/pull/170
   - https://github.com/cal-itp/benefits/issues/175
   - https://github.com/cal-itp/benefits/pull/176
   - https://github.com/cal-itp/benefits/pull/195
- Removed Cypress from devcontainer because of slow build time **(June 2022)**
   - https://github.com/cal-itp/benefits/pull/671
- Disabled Cypress tests from running on pull requests because they were too flaky / were getting in the way of deployments **(June 2022)**
   - https://github.com/cal-itp/benefits/pull/721
- Created a ticket for using Cypress to do automated smoke testing **(Jul 2022)**
   - https://github.com/cal-itp/benefits/issues/813
- Aidan got Cypress tests working again (both "feature" and "UI" tests) **(Feb 2023)**
   - https://github.com/cal-itp/benefits/pull/1263
   - https://github.com/cal-itp/benefits/pull/1277
- Attempts were made to get us back to being able to run Cypress from a container, but never panned out **(Feb 2023)**
   - https://github.com/cal-itp/benefits/issues/681#issuecomment-1433907793
- Closed ticket [#813](https://github.com/cal-itp/benefits/issues/813) for using Cypress for automated smoke testing **(May 2024)**
- Closed ticket [#681](https://github.com/cal-itp/benefits/issues/681) for running Cypress from a container **(Aug 2024)**
</details>

### CODE REVIEW

**Review by thekaveman — APPROVED** [review]
YES PLEASE

image

We'll need to edit the check settings to remove the `tests-cypress` requirement :sweat_smile: 

image

**Comment by angela-tran** [comment]
> We'll need to edit the check settings to remove the `tests-cypress` requirement :sweat_smile: 

Thanks, I can do that now!

**Comment by angela-tran** [comment]
Removed `test-cypress` from `dev` and `test` branch protection rules. `prod`'s rules did not require the check.

**Comment by thekaveman** [comment]
@angela-tran

> Removed test-cypress from `dev` and `test` branch protection rules. `prod`'s rules did not require the check.

Hopefully from `main` as well? Since we don't use those other branches anymore :grin:

**Pull request merged**
