### PR TITLE
Chore: Help copy - Littlepay

### PR DESCRIPTION
**Pull request by angela-tran**
Part of #1544 

This PR updates the section explaining what Littlepay is. Reuses msgids from modal.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
image
image


@angela-tran @srhhnry Is there a decided official style on whether the `.` comes before or after the external link arrow? I personally prefer the `.` comes after the external link arrow (even though the code is a little more annoying for that). 

And should that same style apply to the modal question mark icon?

image

**Comment by srhhnry** [comment]
Yup, punctuation after the icon per the [Styleguide](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=4890-17182&mode=design) (info on the desktop template under the Text Layout section). 

It's been sort of difficult to portray that in Figma because the Google Sheets Sync doesn't interact with components (like the modal button, for instance), so I've added punctuation in manually where I see it, but any space adjustment or resync of the sheet can create spacing issues (:-/).

**Comment by srhhnry** [comment]
Also, just a heads up, punctuation after icon is based on USWDS: https://designsystem.digital.gov/components/link/

**Comment by angela-tran** [comment]
Sounds good @srhhnry , and thank you @machikoyasuda for asking for this to be clarified! I was going off the punctuation shown in the individual screens, but now I know to reference the Style Guide. I will fix

**Comment by angela-tran** [comment]
Dropped the commit that was solely for moving the period inside the link. Will open a separate PR to fix the other external link punctuation in the app

**Review by machikoyasuda — APPROVED** [review]

**Review by thekaveman — APPROVED** [review]

**Pull request merged**
