### PR TITLE
Refactor: Eligibility start page

### LINKED ISSUE #1477: Eligibility Start - Continue to VA.gov button style logic
Need to remove Login.gov logo from button

### PR DESCRIPTION
**Pull request by thekaveman**
Supersedes #1488 -- ultimately moved away from Django template tags in favor of our trusty includes. 

Stole some ideas from #1489 

Part of #1442 

Closes #1477 

## Goals

- [ ] Move as much copy as possible away from the database (models), towards the templates
- [ ] Reduce or eliminate the reliance on view model classes
- [ ] Change incrementally, don't break existing pages/flows
- [ ] Address the points in this comment: https://github.com/cal-itp/benefits/issues/1442#issuecomment-1610326897

## Overview

1. Add field on `EligibilityVerifier` to reference a custom template for Start page
2. Create 3 customized Start templates extending `eligibility/start.html`
    * `eligibility/start__login_gov.html`
    * `eligibility/start__mst_courtesy_card.html`
    * `eligibility/start__veteran.html`
3. Move corresponding copy from model fields into customized template files
4. Change `eligibility:start` view to use the verifier's template

### CODE REVIEW

**Review by machikoyasuda — CHANGES_REQUESTED** [review]
LGTM! 

I tried editing the `start.html` file (removing the whole `help-text` section) to see how the includes would respond and it worked perfectly + quickly (the whole section should be removed, even if the includes calls for it). Sticking with the trusty includes has led to code that's easier for me to read - no more djLint on/off switches - and more plain HTML/regular includes block overrides.

One change request: I believe the `secondary_details` code I wrote last Sprint can be deleted:
- remove parameter from MediaItem view model
- remove from `media-list.html` template

**Review by machikoyasuda — DISMISSED** [review]

**Comment by thekaveman** [comment]
Rebased on the changes in #1489

**Comment by thekaveman** [comment]
Let's get #1499 and #1501 in first since those are simpler, it would be more challenging to rebase/deal with conflicts in both of them against this branch.

**Review by angela-tran — COMMENTED** [review]
This is looking really good so far!

**Comment by thekaveman** [comment]
Ready for re-review. 

I couldn't fully get rid of the tag work from #1488, but I tried to squash it down to a few logical commits for the structure, and one big refactor for the includes.

Thanks for all the comments on the earlier PR, and the radio buttons PR, that all helped clarify a better way forward.

**Review by angela-tran — APPROVED** [review]
I've read through the code changes and run the app locally. This refactor looks great!! 💯

**Review by machikoyasuda — APPROVED** [review]

**Pull request merged**
