### PR TITLE
Docs: Add YouTube videos for enrollment pathways

### PR DESCRIPTION
**Pull request by machikoyasuda**
Replace GIF with nice YouTube videos: https://www.youtube.com/@cal-itp3132

Preview pages:
- https://benefits-1924--cal-itp-previews.netlify.app/enrollment-pathways/agency-cards/
- https://benefits-1924--cal-itp-previews.netlify.app/enrollment-pathways/older-adults/
- https://benefits-1924--cal-itp-previews.netlify.app/enrollment-pathways/veterans/

### CODE REVIEW

**Review by thekaveman — COMMENTED** [review]
This looks good. One question, do we still need the GIF file in the repo? 

https://github.com/cal-itp/benefits/blob/dev/docs/enrollment-pathways/img/senior-success.gif

**Review by indexing — APPROVED** [review]
The video embeds work for me. Thanks!

**Comment by machikoyasuda** [comment]
> https://github.com/cal-itp/benefits/blob/dev/docs/enrollment-pathways/img/senior-success.gif

As long as no one is using this link anywhere..! MST isn't, so we should be good.

**Review by indexing — APPROVED** [review]
I appreciate a little house-keeping.

**Comment by machikoyasuda** [comment]
This is set to automerge as soon as @thekaveman or @angela-tran approves. Thank you!

**Review by angela-tran — APPROVED** [review]

**Pull request merged**
