### PR TITLE
Fix: payment options content

### LINKED ISSUE #272: Text updates for /payment-options (will need Spanish translation)
Please make the following changes on the /payment-options page, as requested by Gillian and Visa (which flagged that Contactless Symbol is a registered trademark and not the symbol we have been showing on this page, which is known as a Contactless Indicator; I have softened this language so we can keep everything lowercase and not use the capitalized marks).

**1. First paragraph**
_Please change **from**:_
Cal-ITP is a new program serving all Californians. In order to activate your discount, you need a bank card that has the contactless symbol on it. The contactless symbol is four curved lines and it looks like this:

_**to:**_
Cal-ITP is a new program serving all Californians. In order to activate your discount, you need a contactless-enabled bank card. Cards that are contactless-enabled have the following symbol (four curved lines) on the front or the back of them:

**2. Second-to-last paragraph** 
_Please change **from**:_
We are working to add additional options for people who do not have access to a bank card. Please check back on this website, or get in touch with your local transit provider.

_**to:**_
Don't have access to a bank card? You can request a contactless card from one of the companies that offer free contactless prepaid debit cards, such as the [Cash App Visa Debit Card](https://cash.app/help/us/en-us/14425-cal-transit) or the [Venmo Mastercard Debit Card](https://venmo.com/about/debitcard/).

_Please note: These changes will need to be translated into Spanish (MST should be able to support; @o-ram can coordinate this ask unless there's another translation solve available)._

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #272

### CODE REVIEW

**Review by angela-tran — APPROVED** [review]
I tested this locally, and it looks good. 👍 

I remember we had discussed trying to find alternatives to the current approach of breaking up the text (as you mentioned in [#272](https://github.com/cal-itp/benefits/issues/272#issuecomment-1004470643)) . I haven't come across anything promising yet, but I'll keep the idea in mind.

**Review by machikoyasuda — APPROVED** [review]
image
image
LGTM!


I also manually ran Google Lighthouse on the payment options page: No regressions and the links properly have `noreferrer` set.

image

**Comment by machikoyasuda** [comment]
Think this is some bug on my machine/Docker but when I build the container for this branch

I get this still

image



Just putting this comment here for my own memory. I hope this resolves itself..

**Comment by thekaveman** [comment]
@machikoyasuda I see that everyone once in a while too (I think it is unrelated to this change though).

We are supposed to commit changes to that `package-lock.json` file, but I usually just ignore them / `git reset` the file and let Dependabot update it when `package.json` is updated.

**Pull request merged**
