### PR TITLE
Veterans: add Sign Out link for Veterans/Login.gov flow

### LINKED ISSUE #1707: Veteran enrollment pathway: display Login.gov sign-out button views following identity verification
When a rider chooses the US Veteran option for Benefits enrollment, they will utilize Login.gov (see #1691 for context). After a veteran completes identity verification, they will see a series views in the Benefits app depending on the verification response. (See the the [login flow](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5766%3A22626&mode=design&t=cLR0Gycsisf0pNvS-1) in Figma.) The app needs to present the option to sign out of Login.gov once identity verification is complete.

## Acceptance Criteria

- [ ] Display _Sign out of Login_ button on `Enrollment` view
- [ ] Display _Sign out of Login_ button on `Eligibility Error` view
- [ ] Display _Sign out of Login_ button on `Payment Error` view
- [ ] Display _Sign out of Login_ button on `Success` view

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #1707 

## What this PR does
- Rename the `button--sign-out--senior` and `link--sign-out--senior` files to use `--login-gov` suffix
- Add `sign_out_button_template`, `sign_out_link_template` to Veteran's

## How to test this PR
For the Veterans flow and the Senior flow:
- Display Sign out of Login button on Enrollment view
- Display Sign out of Login button on Eligibility Error view This one is hard to test)
- Display Sign out of Login button on Payment Error view (This one is hard to test)
- Display Sign out of Login button on Enrollment Success view

## How I tested this locally
- Since the Login.gov/VA IDG flow is not yet available, I faked it by setting my VA Auth Provider to have the same exact configuration as the Senior one, and went thru the flow to at least confirm that the sign out link and buttons are showing up:
image
image

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Ready for review @thekaveman @angela-tran

**Comment by thekaveman** [comment]
@machikoyasuda @angela-tran 

> Since the Login.gov/VA IDG flow is not yet available

It is now available and should work from `localhost:11369` and `dev-benefits`, see this long thread in Slack for configuration details: https://cal-itp.slack.com/archives/C037Y3UE71P/p1694210616556309

I updated the [Benefits Test Data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit#heading=h.bvwe1dyv15c5) doc with info about how to create a sandbox Login.gov user that verifies as a Veteran.

**Comment by thekaveman** [comment]
@machikoyasuda want to rebase this on the changes from those other PRs?

**Comment by machikoyasuda** [comment]
Tested locally: Veterans log out
image
image

**Review by thekaveman — APPROVED** [review]
Looks good. I see the link and was able to sign out from:

✅ Eligibility Fail
✅ Enrollment Start
✅ Enrollment Success

**Pull request merged**
