### PR TITLE
Chore: remove AWS deployment

### PR DESCRIPTION
**Pull request by thekaveman**
We've migrated the app to Azure hosting. This PR removes the AWS deployment bits and updates the docs to reflect the new hosting situation.

Once this PR is merged, the 3 GitHub environments `dev`, `test`, and `prod` can be deleted as their secrets are no longer needed.

### CODE REVIEW

**Comment by thekaveman** [comment]
Incoming rebase to clean up conflicts.

**Comment by thekaveman** [comment]
Blocked while we fully configure the dev slot as part of #615

**Comment by thekaveman** [comment]
Ready for review now that the dev slot is fully configured

**Review by angela-tran — COMMENTED** [review]
This looks great! Do we want to remove the parts of our docs that talk about [AWS environment variables](https://github.com/cal-itp/benefits/blob/79706fdffe3f6a662430b5cbf794d31529d8e2cf/docs/configuration/environment-variables.md#aws)?

**Review by machikoyasuda — APPROVED** [review]
🎊🎊🎊

**Pull request merged**
