### PR TITLE
Refactor: Remove CA State Web Template

### LINKED ISSUE #2491: Web perf: Remove CA State Web Template
This ticket is part of a group of web performance tickets tracked here https://github.com/cal-itp/benefits/issues/2487.

## Acceptance Criteria

- [ ] Remove CA State Web Template, replace with regular Bootstrap CDN call
- [ ] Write/fix any CSS necessary to ensure no regressions

## Additional context

- Make sure to test: JS / No Cookies banner, all the banners - just enable them manually with HTML, focus states, skip nav
- Run Lighthouse performance test before and after to compare page weight

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #2491 

## What this PR does
- Remove CA State Web Template CSS, which will then remove the call to the CA State Web Template font
- Remove CA State Web Template domain from CSP
- Makes any CSS fixes necessary

## Changelog
- fix:`text-left` to `text-start`
- fix: add css to fix skip nav
- fix: button focuses
- slight refactor: buttons in general. could be greatly refactored to mostly be written with css variables instead, reducing the number of new classes/modified classes.

## QA
- Trigger the skip nav
- Go through the whole app via keyboard, paying attention to the way the modals behave with the radio buttons
- Manually enable the JavaScript/Cookies warnings via HTML (remove the no display class) and compare it visually with the current one
- Check the app on responsive widths

### CODE REVIEW

**Comment by thekaveman** [comment]
> fix:`text-left` to `text-start`

Was this a CA State Web Template class, and now we use the Bootstrap version or?

**Review by thekaveman — COMMENTED** [review]
I'm noticing some slight differences between this branch and `prod` -- not necessarily a bad thing, just wondering if you have any more insight:

<details>
<summary>Homepage text is better aligned</summary>

|     | This branch | `prod` |
|----| ----------------- | --------- | 
| `992px` | image | image |
| `1200px` | image | image |

</details>

<details>
<summary>Overall container/spacing is better on larger screen sizes</summary>

|     | This branch | `prod` |
|----| ----------------- | --------- | 
| `1280px` | image | image |
| `1280px` | image| image |

</details>

**Comment by machikoyasuda** [comment]
> > fix:`text-left` to `text-start`
> 
> Was this a CA State Web Template class, and now we use the Bootstrap version or?

In general: It's actually more of a CSS change. `text-align: start` works now. Check it out here: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

Using start/end instead of left/right is a way for CSS to be more "content-aware" (is the term I've seen used) which in this context means that if the language of the HTML document is a Right to Left language, the `text-align: start` woould set `text-align: right`, and on Left to Right language, `text-align: start` would set `text-align: left`.

**Comment by machikoyasuda** [comment]
@thekaveman Your width change noticings also reflect how CA State Web Template had some different numbers for container max-widths, and now we're on Bootstrap's defaults.

**Review by thekaveman — APPROVED** [review]

**Comment by thekaveman** [comment]
- Triggered skip nav :white_check_mark: 
- Went through the app with keyboard only :white_check_mark: 
- Manually enabled JavaScript/cookie warnings (the text on these is still not contrasted enough) :white_check_mark: 
- Checked the app on various responsive widths :white_check_mark:

**Pull request merged**
