### PR TITLE
Docs: add manual qa instructions

### LINKED ISSUE #1690: Document overview of manual / QA testing process
## Acceptance criteria

- [x] A page/section is added to https://docs.calitp.org/benefits/tests/ for "Manual tests" that 1) outlines the procedure below and 2) prominently links to the [Benefits Test Data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing) document.

## Original write-up

In order to do a thorough review of the app, I've provided some guidance below. This approach adds some complexity to the process, but I don't see how you'll be able to see different aspects of the app in context without using test data. Feel free to jump directly to step 8 and review directly in the Copy master spreadsheet. It does include links to individual views for context.

--- 

# Instructions for reviewing Spanish translation of the Benefits app

To access various views in the app, you will need to follow several enrollment pathways in the application. Please do not use your personal accounts for Login.gov, ID.me, etc. to complete your review. We have a set of test accounts and test data available in [Benefits Test Data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing). 

1. Open the Benefits application in our test environment using a supported browser. <https://test-benefits.calitp.org/>

2. Switch the application language to Spanish using the button labeled *Español* on the right side of the app header.

3. Choose MST as your transit agency.

4. Follow the *Older Adult* enrollment pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing).

5. Follow the *Veterans* enrollment pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing).

6. Follow the *Courtesy Card* pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing).

7. Review the Help page.

8. Jot down any issues or notes during the review. Highlight any proposed changes on the *forTranslation* tab in the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) spreadsheet. Use the comment feature in Google Sheets to share your feedback. Please mention Andy Walker and Machiko Yasuda in each comment.

_Originally posted by @indexing in https://github.com/cal-itp/benefits/issues/1584#issuecomment-1693781155_

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #1690

Note: Bolding user interface elements (like **Create an account**) follows the Google developer documentation style guide: https://developers.google.com/style/ui-elements

image
image
image
image

### CODE REVIEW

**Comment by machikoyasuda** [comment]
The manual QA docs are also now ready for review @angela-tran @indexing - I aimed to further clarify how to get through the Login.gov process for people who are new to it. I added @indexing's Spanish translation check guide - edited for style. Also added a Keyboard testing guide for accessibility.

**Review by indexing — APPROVED** [review]
It'll be nice to have these testing instructions available for easy referance.

**Comment by machikoyasuda** [comment]
Needs final review from @angela-tran (codeowner)

**Review by angela-tran — APPROVED** [review]
This looks good to me. Thanks @machikoyasuda

**Pull request merged**
