### PR TITLE
CodeQL scanning workflow

### PR DESCRIPTION
**Pull request by thekaveman**
https://codeql.github.com/docs/codeql-overview/about-codeql/

> CodeQL is the analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis.

Runs on:

* PR to `dev`
* Push to `dev`, `test`, `prod`
* Weekly on Saturdays

See the scan results under the *Security* tab of this repo: https://github.com/cal-itp/benefits/security/code-scanning

### CODE REVIEW

**Comment by thekaveman** [comment]
@machikoyasuda I don't know what is going on with the `tests-ui` check... seems like the same issue you were having the other night, it won't run/pass!? Even though it shouldn't even have to run on this PR, since we didn't change any files matching the `path` filters in that workflow...?

Did you ever find out what was going on? Or did it just work eventually?

**Review by angela-tran — APPROVED** [review]
I read the README from https://github.com/github/codeql-action to familiarize myself with this tool. This workflow file looks good to me 👍

**Comment by angela-tran** [comment]
> @machikoyasuda I don't know what is going on with the `tests-ui` check... seems like the same issue you were having the other night, it won't run/pass!? Even though it shouldn't even have to run on this PR, since we didn't change any files matching the `path` filters in that workflow...?
> 
> Did you ever find out what was going on? Or did it just work eventually?

Maybe the problem is that the `tests-ui` workflow is set as **Required** to merge in the branch, but in this pull request, the check is not going to actually run.

That is my guess based on this post: https://github.community/t/expected-waiting-for-status-to-be-reported/18001

**Comment by thekaveman** [comment]
Boo. Maybe if we merge #238 and rebase this one on top... we can manually run the tests job and it will notice?

**Comment by angela-tran** [comment]
I think that would work / get us un-stuck.

**Comment by thekaveman** [comment]
Closing to rebase/reopen on `dev`.

**Pull request closed without merging**
