### PR TITLE
Index, Agency Index: Copy update

### LINKED ISSUE #1386: Home & Agency Index - Update homepage copy + Create Agency text variables
Update home page copy to be more concise for users.

image

## Acceptance criteria

- [x] Draft English Copy written
- [x] Copy ready for translation vendor 
- [x] Spanish copy added to app
- [x] Execute/ test new process for updating copy and working with content localization vendor

## Definition of "Done"

- [x] New homepage copy published in English
- [x] New homepage copy published in Spanish

## Links to user research, designs and resources

- [Finalized Figma file Desktop](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application))
- [Finalized Figma file Mobile](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application))

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #1386 

The Figma designs and Copy spreadsheet call for 2 changes that are not reflected in this PR:
- This PR does NOT change the capitalization of `Choose Your Provider.` This change should happen when `Choose This Benefit` is also changed for consistency.
- This PR does NOT add a way to distinguish between `public transportation` or `light rail`. This PR uses `public transportation` as a default for all agencies.

## Index
image
image

### MST
image

### SacRT
image

### CODE REVIEW

**Review by thekaveman — COMMENTED** [review]
Does it make sense to say this PR closes #1386 if it's just hardcoding to one of the copy updates? Figma shows we need to be able to swap in `[Agency short name]` and `[Agency transit type]`.  I fear that will drop off our radar if we close that issue here.

I think either don't close that issue with this PR just to make this small update, or add the `transit type` string to the model and use it here.

**Comment by thekaveman** [comment]
> This PR does NOT change the capitalization of Choose Your Provider. This change should happen when Choose This Benefit is also changed for consistency.

I'm also not sure I agree with this -- again if we're saying this PR closes #1386, then it should update the copy on the homepage, including the button: https://github.com/cal-itp/benefits/blob/dev/benefits/locale/en/LC_MESSAGES/django.po#L455

"Choose this Benefit" and the changes there are not part of the homepage right?

**Comment by machikoyasuda** [comment]
@thekaveman Yeah - I mean, I could change `Choose Your Provider` to `Choose your Provider`. But then.. the app will have different button capitalization throughout the app. Which is fine I guess (?)

**Comment by machikoyasuda** [comment]
I made a draft GitHub issue to change button pronoun capitalization throughout the app uniformly here: https://github.com/orgs/cal-itp/projects/17/views/2?pane=issue&itemId=31905444

**Comment by machikoyasuda** [comment]
@thekaveman And yes, the `[Agency transit type]` issue actually something that may need to be deployed before a SacRT launch.

We never coded logic for `[Agency transit type]` so the current Test site's SacRT flow's copy here is potentially factually incorrect if SacRT does not have contactless pay on their buses:
image

So once we get word from Product (@vykster @indexing) of whether this copy change is on Eligibility Index is necessary or not, we can make a ticket to do it. 

The homepage copy update issue was not intended to include the creation of the `[Agency transit type]` .

**Comment by thekaveman** [comment]
> @thekaveman Yeah - I mean, I could change `Choose Your Provider` to `Choose your Provider`. But then.. the app will have different button capitalization throughout the app. Which is fine I guess (?)

Given your original translation request from #1386 included this button: https://github.com/cal-itp/benefits/issues/1386#issuecomment-1532324772

> These are the strings I sent in the request: 
> image

I'm inclined to say that this PR should fully update all text on the homepage.

**Comment by machikoyasuda** [comment]
Closing for the time being & moving this to next Sprint b/c there's more code changes necessary than I originally thought

**Pull request closed without merging**
