### PR TITLE
Refactor: error page layout and wording

### LINKED ISSUE #757: Better handling of visiting restricted pages
There's probably a better way to word that title.

## To Reproduce

1. Open an Incognito/Private Window
2. Go to https://test-benefits.calitp.org/enrollment/
3. See `Service is down` error message

## Expected behavior

I would expect the user to get redirected to the start of the flow, or at least shown a message like "we need you to do a few things before you can access this page."

## Screenshots

Screen Shot 2022-06-29 at 1 19 54 PM

## Desktop

- OS: macOS 12.4
- Browser: Firefox v101.0.1

## Additional context

n/a

### LINKED ISSUE #914: Move all 404/500/error pages to the One Column Layout
## Acceptance Criteria

- [x] 404, 500 pages move to 1 column layout
- [x] Use the “Enrollment redirect” error mock for 404s and 500s resulting from the user not entering the app at the correct phase, e.g. no agency selected, no verifier selected, not verified as eligible yet

## Additional context

See Figma

Related to #913 https://github.com/cal-itp/benefits/issues/757

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #914 (and closes #757 ?)

| Scenario | Before | After |
| --- | --- | --- |
| Navigate to a page earlier than you should | image | image |
| Page not found (404) | image | image |

### Scenario: Navigate to a page earlier than you should
1. Launch benefits via the VS Code debugger (choose config with `Debug=False`) 
1. Start on the home page (e.g. `http://localhost:11369/`)
1. Using the URL bar, go to a page much later in the flow (e.g. `http://localhost:11369/enrollment`)

**Expected result**: one-column error page saying that the user may have reached this page on accident.

### Scenario: Page not found (404)
1. Launch benefits via the VS Code debugger (choose config with `Debug=False`)
1. Start on the home page (e.g. `http://localhost:11369`)
1. Using the URL bar, go to a nonexistent page

**Expected result**: one-column error page saying that the user may have reached this page on accident.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@angela-tran Can you add instructions on how to test these pages/flows out?

**Comment by machikoyasuda** [comment]
Tested:

English 500 
image


Spanish 500 image

**Review by thekaveman — APPROVED** [review]
Very nice, I walked through both scenarios locally and everything looks good.

The tests you added here are great! Thank you for that.

**Comment by machikoyasuda** [comment]
@angela-tran thank you for the wonderful instructions

**Review by machikoyasuda — APPROVED** [review]

**Pull request merged**
