### PR TITLE
Docs updates

### LINKED ISSUE #117: Update docs re: production branch name
@thekaveman https://docs.calitp.org/benefits/getting-started/development/ - should update this doc: https://github.com/cal-itp/benefits/blob/dev/docs/getting-started/development.md

_Originally posted by @machikoyasuda in https://github.com/cal-itp/benefits/issues/116#issuecomment-923198768_

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #117. Plus some other small cleanups and a new page describing the GitHub Actions deployment workflows in more detail.

### CODE REVIEW

**Review by machikoyasuda — APPROVED** [review]

**Comment by thekaveman** [comment]
Thanks for the review @machikoyasuda! I'm going to wait to merge this until #114 is merged so we can test out that filter!

**Review by machikoyasuda — APPROVED** [review]
Very thorough!

**Comment by machikoyasuda** [comment]
#114 is now merged to `dev`. #118 is ready to roll!

**Comment by thekaveman** [comment]
I'll actually wait for #115 as well, so we can test both filters 😄

**Comment by machikoyasuda** [comment]
@thekaveman Update: Merged #115 - As expected, the Docs deploy action is _**not**_ running. Now this PR is ready to roll! We should expect the Docs deploy to run, but the Dev deploy should not run.

image

**Comment by thekaveman** [comment]
@machiko awesome! I'm merging this one now...

**Pull request merged**
