### PR TITLE
Enrollment Success: Desktop - Bring text/img closer together

### LINKED ISSUE #1638: Bug: Enrollment Success - Desktop: Image spacing is off
Image should be 16px away from the text.

image

### PR DESCRIPTION
**Pull request by machikoyasuda**
fix #1638 

## What this PR does
- Remove `offset-lg-1`
- Change `col-lg-6` to `col-lg-7`
- No changes to mobile

## Screenshot
image

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@srhhnry How does the above page look?

I could also widen the text to be 7 columns, not 6. That looks like this:
image

**Comment by srhhnry** [comment]
Second image looks more centered against the headline, so let's go that direction

**Comment by machikoyasuda** [comment]
@srhhnry Awesome - thank you. The 7-column/5-column grid combo matches Figma best:

image

**Comment by machikoyasuda** [comment]
Ready for engineering review @angela-tran

**Review by angela-tran — APPROVED** [review]

**Pull request merged**
