### PR TITLE
Refactor: remove Page viewmodel

### LINKED ISSUE #1442: Refactor usage of view models
As shown in #1436, adding or moving around copy driven by translations requires changes in multiple places:

* models, to reference the PO entries
* PO files, to hold the translations
* view view models, to get the data into the view

We need to look into how to simplify this, ideally cutting out extraneous view models that already have a corresponding model, and sending that directly to the template instead.

## Plan

After some different iterations, this is the approach we landed on:

* Move all translated strings out of models, and as close to the templates (HTML) as possible
* Use fields in the models to reference template variants when needed (e.g. for TransitAgency and EligibilityVerifier)
* Simplify the views as much as possible: remove usage of viewmodels, create basic dictionary context that has exactly the fields needed for that view/page

## Acceptance Criteria

The following `viewmodels` and helpers are removed:

- [x] `viewmodels.Button` #1562
  - [x] `viewmodels.Button.agency_contact_links` #1521
  - [x] `viewmodels.Button.home` #1522
  - [x] `viewmodels.Button.link` #1521
  - [x] `viewmodels.Button.login` #1498
  - [x] `viewmodels.Button.logout` #1534
  - [x] `viewmodels.Button.primary` #1562
  - [x] `viewmodels.Button.outline_primary` #1562
  - [x] `viewmodels.Button.previous_page` #1562
- [x] `viewmodels.Icon` #1542
- [x] `viewmodels.MediaItem` #1542
- [x] `viewmodels.Modal` #1504
  - [x] `viewmodels.AgencySelector` #1504
- [ ] `viewmodels.Page` #1563
- [x] `viewmodels.ErrorPage` #1536
  - [x] `viewmodels.ErrorPage.user_error`  #1536
  - [x] `viewmodels.ErrorPage.server_error`  #1536
  - [x] `viewmodels.ErrorPage.not_found`  #1536
- [x] `viewmodels.PaymentProcessor` #1502
- [x] `viewmodels.TransitAgency` #1541

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #1442 as the final `viewmodels.Page` is removed and the module is deleted.

### CODE REVIEW

**Comment by thekaveman** [comment]
I'm going to rebase this on #1566 since they both touch the homepage, but this one more significantly, to deal with conflicts now vs. later.

**Comment by thekaveman** [comment]
> I'm going to rebase this on #1566 since they both touch the homepage, but this one more significantly, to deal with conflicts now vs. later.

Since this PR is already on the latest `dev`, and #1566 is still behind the latest `dev`, I'm just going to hold this one until #1566 is merged and rebase then.

**Review by machikoyasuda — APPROVED** [review]
Went thru full flow for Courtesy Card, went thru Help page, went thru both Agency Indexes, tested headlines/titles

**Comment by thekaveman** [comment]
Rebased on latest `dev` to resolve conflicts.

**Review by machikoyasuda — APPROVED** [review]
lgtm 👍 

fixes the current issue on dev where some of the page titles have an extra space after the `|  ...`

**Review by angela-tran — APPROVED** [review]
🚀

**Pull request merged**
